#!/bin/bash
desired_screen_count=<COUNT>
screen_count=$(screen -list | grep Sockets | grep -oP '(\d+)')

if [[ $screen_count < $desired_screen_count ]]; then
        amt_to_spawn=$(($desired_screen_count-$screen_count))
        for i in $( seq 1 $amt_to_spawn )
        do
                $(screen -dm bash -c '<COMMAND>')
        done
fi
